export type Product = {
  slug: string; brand: string; name: string; type: "Full bottle" | "Decant"; gender: "Men" | "Women" | "Unisex"; family: string; price: number; sizePrices?: Record<string, number>; compareAt?: number; sizes: string[]; image: string; description: string; notes: { top: string[]; heart: string[]; base: string[] }; featured?: boolean; newArrival?: boolean;
};

export const products: Product[] = [
  { slug: "maison-margiela-replica-jazz-club", brand: "Maison Margiela", name: "REPLICA Jazz Club", type: "Full bottle", gender: "Unisex", family: "Woody", price: 48500, sizes: ["100ml"], image: "https://images.unsplash.com/photo-1590736704728-f4730bb30770?auto=format&fit=crop&w=900&q=85", description: "A warm, smoky composition inspired by the intimate atmosphere of a Brooklyn jazz club.", notes: { top: ["Pink Pepper", "Neroli"], heart: ["Rum", "Clary Sage"], base: ["Tobacco Leaf", "Vanilla"] }, featured: true },
  { slug: "diptyque-eau-rose", brand: "Diptyque", name: "Eau Rose Eau de Toilette", type: "Full bottle", gender: "Women", family: "Floral", price: 36000, sizePrices: { "50ml": 36000, "100ml": 56000 }, sizes: ["50ml", "100ml"], image: "https://images.unsplash.com/photo-1587017539504-67cfbddac569?auto=format&fit=crop&w=900&q=85", description: "A fresh, generous rose built around the whole flower, from petal to leaf.", notes: { top: ["Litchi", "Blackcurrant"], heart: ["Damask Rose", "Grasse Rose"], base: ["Musk", "Cedar"] }, featured: true },
  { slug: "le-labo-santal-33", brand: "Le Labo", name: "Santal 33", type: "Full bottle", gender: "Unisex", family: "Woody", price: 62000, sizePrices: { "50ml": 62000, "100ml": 89000 }, compareAt: 68000, sizes: ["50ml", "100ml"], image: "https://images.unsplash.com/photo-1600612253971-422e7f7faeb6?auto=format&fit=crop&w=900&q=85", description: "An addictive, smoky woods fragrance with an unmistakable signature.", notes: { top: ["Cardamom", "Violet Accord"], heart: ["Papyrus", "Iris"], base: ["Australian Sandalwood", "Cedar"] }, featured: true },
  { slug: "byredo-bal-dafrique-decant", brand: "Byredo", name: "Bal d’Afrique", type: "Decant", gender: "Unisex", family: "Citrus", price: 2200, sizePrices: { "2ml": 2200, "5ml": 4900, "10ml": 9200, "20ml": 17600 }, sizes: ["2ml", "5ml", "10ml", "20ml"], image: "https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?auto=format&fit=crop&w=900&q=85", description: "A vibrant, joyful fragrance where neroli and African marigold meet warm woods.", notes: { top: ["Bergamot", "Lemon"], heart: ["Violet", "Jasmine"], base: ["Cedar", "Musk"] }, featured: true },
  { slug: "nishane-hacivat-decant", brand: "Nishane", name: "Hacivat", type: "Decant", gender: "Unisex", family: "Fresh", price: 2800, sizePrices: { "2ml": 2800, "5ml": 6500, "10ml": 12400, "20ml": 23900 }, sizes: ["2ml", "5ml", "10ml", "20ml"], image: "https://images.unsplash.com/photo-1557170334-a9632e77c6e4?auto=format&fit=crop&w=900&q=85", description: "A sparkling tribute to elegance, with a crisp opening and mossy depth.", notes: { top: ["Pineapple", "Bergamot"], heart: ["Jasmine", "Patchouli"], base: ["Oakmoss", "Woody Notes"] }, newArrival: true },
  { slug: "armani-my-way", brand: "Giorgio Armani", name: "My Way Eau de Parfum", type: "Full bottle", gender: "Women", family: "Floral", price: 39500, sizePrices: { "30ml": 39500, "50ml": 58500, "90ml": 84900 }, sizes: ["30ml", "50ml", "90ml"], image: "https://images.unsplash.com/photo-1595535373192-fc8935bacd89?auto=format&fit=crop&w=900&q=85", description: "A bright floral bouquet for a new generation of open-minded women.", notes: { top: ["Orange Blossom", "Bergamot"], heart: ["Tuberose", "Indian Jasmine"], base: ["Cedarwood", "Vanilla"] }, newArrival: true },
  { slug: "dior-sauvage-elixir", brand: "Dior", name: "Sauvage Eau de Parfum", type: "Full bottle", gender: "Men", family: "Fresh", price: 46500, sizePrices: { "60ml": 46500, "100ml": 68500 }, sizes: ["60ml", "100ml"], image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=900&q=85", description: "A confident fresh-amber scent with bergamot, spice and a smooth woody trail.", notes: { top: ["Bergamot", "Pepper"], heart: ["Lavender", "Star Anise"], base: ["Ambroxan", "Vanilla"] }, featured: true },
  { slug: "bleu-de-chanel-edp", brand: "Chanel", name: "Bleu de Chanel Eau de Parfum", type: "Full bottle", gender: "Men", family: "Woody", price: 59800, sizePrices: { "50ml": 59800, "100ml": 82500 }, sizes: ["50ml", "100ml"], image: "https://images.unsplash.com/photo-1615634260167-c8cdede054de?auto=format&fit=crop&w=900&q=85", description: "A polished aromatic-woody fragrance that balances citrus, incense and cedar.", notes: { top: ["Grapefruit", "Lemon"], heart: ["Ginger", "Jasmine"], base: ["Incense", "Cedar"] }, newArrival: true },
  { slug: "ysl-libre-edp", brand: "Yves Saint Laurent", name: "Libre Eau de Parfum", type: "Full bottle", gender: "Women", family: "Floral", price: 38500, sizePrices: { "30ml": 38500, "50ml": 54800, "90ml": 74800 }, sizes: ["30ml", "50ml", "90ml"], image: "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=900&q=85", description: "A luminous contrast of orange blossom, lavender and warm vanilla.", notes: { top: ["Mandarin", "Blackcurrant"], heart: ["Orange Blossom", "Lavender"], base: ["Vanilla", "Cedar"] }, featured: true },
  { slug: "chanel-coco-mademoiselle", brand: "Chanel", name: "Coco Mademoiselle", type: "Full bottle", gender: "Women", family: "Amber", price: 76500, sizePrices: { "50ml": 76500, "100ml": 108000 }, sizes: ["50ml", "100ml"], image: "https://images.unsplash.com/photo-1587017539504-67cfbddac569?auto=format&fit=crop&w=900&q=85", description: "A bright, elegant amber-floral scent with sparkling citrus and soft patchouli.", notes: { top: ["Orange", "Bergamot"], heart: ["Rose", "Jasmine"], base: ["Patchouli", "Vanilla"] }, newArrival: true },
  { slug: "tom-ford-oud-wood", brand: "Tom Ford", name: "Oud Wood", type: "Full bottle", gender: "Unisex", family: "Woody", price: 128000, sizePrices: { "50ml": 128000, "100ml": 182000 }, sizes: ["50ml", "100ml"], image: "https://images.unsplash.com/photo-1600612253971-422e7f7faeb6?auto=format&fit=crop&w=900&q=85", description: "Rare oud and dark woods softened by cardamom, amber and creamy vanilla.", notes: { top: ["Cardamom", "Pink Pepper"], heart: ["Oud", "Sandalwood"], base: ["Amber", "Vanilla"] }, featured: true },
  { slug: "mfk-baccarat-rouge-decant", brand: "Maison Francis Kurkdjian", name: "Baccarat Rouge 540", type: "Decant", gender: "Unisex", family: "Amber", price: 4900, sizePrices: { "2ml": 4900, "5ml": 11900, "10ml": 22900, "20ml": 44500 }, sizes: ["2ml", "5ml", "10ml", "20ml"], image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=900&q=85", description: "An airy amber accord with luminous saffron and a warm, lasting woody sweetness.", notes: { top: ["Saffron", "Jasmine"], heart: ["Amberwood", "Ambergris Accord"], base: ["Fir Resin", "Cedar"] }, newArrival: true },
  { slug: "dior-sauvage-decant", brand: "Dior", name: "Sauvage Eau de Parfum", type: "Decant", gender: "Men", family: "Fresh", price: 2200, sizePrices: { "2ml": 2200, "5ml": 5100, "10ml": 9700, "20ml": 18800 }, sizes: ["2ml", "5ml", "10ml", "20ml"], image: "https://images.unsplash.com/photo-1615634260167-c8cdede054de?auto=format&fit=crop&w=900&q=85", description: "Try the fresh, spicy Sauvage signature in a travel-ready spray decant.", notes: { top: ["Bergamot", "Pepper"], heart: ["Lavender", "Star Anise"], base: ["Ambroxan", "Vanilla"] }, featured: true },
  { slug: "libre-decant", brand: "Yves Saint Laurent", name: "Libre Eau de Parfum", type: "Decant", gender: "Women", family: "Floral", price: 2500, sizePrices: { "2ml": 2500, "5ml": 5900, "10ml": 11200, "20ml": 21800 }, sizes: ["2ml", "5ml", "10ml", "20ml"], image: "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=900&q=85", description: "Take the bold orange blossom and lavender signature with you in a fine spray.", notes: { top: ["Mandarin", "Blackcurrant"], heart: ["Orange Blossom", "Lavender"], base: ["Vanilla", "Cedar"] }, newArrival: true },
  { slug: "oud-wood-decant", brand: "Tom Ford", name: "Oud Wood", type: "Decant", gender: "Unisex", family: "Woody", price: 4200, sizePrices: { "2ml": 4200, "5ml": 10100, "10ml": 19500, "20ml": 37800 }, sizes: ["2ml", "5ml", "10ml", "20ml"], image: "https://images.unsplash.com/photo-1600612253971-422e7f7faeb6?auto=format&fit=crop&w=900&q=85", description: "Discover rare oud, spice and soft woods in a portable spray decant.", notes: { top: ["Cardamom", "Pink Pepper"], heart: ["Oud", "Sandalwood"], base: ["Amber", "Vanilla"] }, featured: true },
];

export const getProductPrice = (product: Product, size = product.sizes[0]) => product.sizePrices?.[size] ?? product.price;

export const formatPrice = (price: number) => `Rs. ${price.toLocaleString("en-LK")}`;